# Generated by Django 5.2.8 on 2025-11-08 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('member', "Membre d'une cooperative")], default='customer', max_length=10)),
                ('user_lastname', models.CharField(max_length=30)),
                ('user_firstname', models.CharField(max_length=60)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_contact', models.CharField(max_length=26, unique=True)),
                ('user_home_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField()),
                ('password', models.CharField()),
                ('last_login', models.DateTimeField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
